spring:
  datasource:
    url: jdbc:h2:mem:testappdb
    driverClassName: org.h2.Driver
    username: sa
    password: ChAng3Me
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console-enabled: true
